#!/bin/bash

# Script para configurar webhook de GitHub en Jenkins
echo "🔗 Configuración de Webhook GitHub → Jenkins"
echo "==========================================="

JENKINS_URL="http://localhost:8090"
JOB_NAME="pokedex-pwa-pipeline"

echo "📋 Información para configurar webhook en GitHub:"
echo ""
echo "🌐 URL del Webhook:"
echo "   ${JENKINS_URL}/github-webhook/"
echo ""
echo "📝 Configuración en GitHub:"
echo "   1. Ve a tu repositorio: https://github.com/Blxckbxll24/pokedexPWA"
echo "   2. Settings → Webhooks → Add webhook"
echo "   3. Payload URL: ${JENKINS_URL}/github-webhook/"
echo "   4. Content type: application/json"
echo "   5. Events: 'Send me everything' o especificar:"
echo "      - Push"
echo "      - Pull requests"
echo "   6. Active: ✅"
echo "   7. Add webhook"
echo ""
echo "🔐 Para webhooks seguros (opcional):"
echo "   - Secret: Puedes generar uno aleatorio"
echo "   - Configurar el mismo secret en Jenkins"
echo ""
echo "⚙️ Configuración adicional en Jenkins:"
echo "   1. Ve a: ${JENKINS_URL}/job/${JOB_NAME}/configure"
echo "   2. En 'Build Triggers', marca:"
echo "      ✅ GitHub hook trigger for GITScm polling"
echo "   3. Si usas secret, configúralo en 'GitHub webhook secret'"
echo ""
echo "🧪 Probar el webhook:"
echo "   1. Haz un push a cualquier rama"
echo "   2. Ve a ${JENKINS_URL} y verifica que el job se ejecute"
echo ""
echo "📞 Solución de problemas:"
echo "   - Verifica que Jenkins sea accesible desde internet"
echo "   - Para desarrollo local, considera usar ngrok:"
echo "     npm install -g ngrok"
echo "     ngrok http 8090"
echo "     Usa la URL de ngrok en lugar de localhost"
echo ""
echo "✅ Una vez configurado, Jenkins detectará automáticamente:"
echo "   - Pushes a develop → Tests + SonarQube"
echo "   - Pushes a main → Tests + SonarQube + Deploy"